version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    restart: always
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    restart: always
  
  meals:
    build: ./meals
    ports:
      - 5001:80
    expose:
      - 80
    restart: always

  diet:
    build: ./diet
    ports:
      - 5002:80
    expose:
      - 80
    restart: always

  
